<a href="https://colab.research.google.com/github/SRMannan/Pytorch_L1/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.3.1+cu121


## INTRO TO TENSORS

created using torch.tensor

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[1,3,5] , [2,4,6]])
MATRIX.shape

torch.Size([2, 3])

In [ ]:
MATRIX[1]

tensor([2, 4, 6])

In [ ]:
TENSOR = torch.tensor([[[1,2,3] , [3,6,9] , [4,8,10]]])
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR2 = torch.tensor([[[[1,2,3] , [1,2,4] , [1,3,8]] , [[2,3,4] , [4,5,6] , [7,8,9]]]])
TENSOR2

tensor([[[[1, 2, 3],
          [1, 2, 4],
          [1, 3, 8]],

         [[2, 3, 4],
          [4, 5, 6],
          [7, 8, 9]]]])

In [ ]:
## 1 , 2 , 3 , 3
TENSOR2.shape

torch.Size([1, 2, 3, 3])

In [ ]:
TENSOR2[0][1][1][1]

tensor(5)

**for scalars and vectors ie tensors of dimension 0 and 1 we use lowercase variable names**

**for matrices and N dimension tensors we use uppercase , just for sake of understanding what is what**

*thats why we used such namings above*

NOW TO RANDOM TENSORS

*why random tensors*
these are very imp since this is the way neural networks learn , they start with tensors full of random numbers and then adjust those random #s to learn and ajust

`start with random numbers -> look at data -> update the random numbers -> repeat`

In [ ]:
#create a random tensor of size/shape(3,4)

random_tensor = torch.rand(1,3,4)
print(random_tensor)
print('DIM : ' , random_tensor.ndim)

tensor([[[0.9687, 0.5579, 0.1333, 0.3204],
         [0.2383, 0.8082, 0.3087, 0.8428],
         [0.8387, 0.7715, 0.4015, 0.4486]]])
DIM :  3


In [ ]:
# create a random tesnor with similar size as that of an image
random_image_size_tensor = torch.rand(size = (3 , 224 , 224))           #color_channels , height , width
#random_image_size_tensor
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([224, 224, 3])
3


# Tensors with all zeros or ones
*this is useful when creating masks* ✈

In [ ]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
#thats masking
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])