<a href="https://colab.research.google.com/github/SRMannan/Pytorch_L1/blob/main/4_PIPELINE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [69]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [70]:
df.shape

(569, 33)

In [71]:
df.drop(columns = ['id' , 'Unnamed: 32'] , inplace = True)

In [72]:
df.sample(20)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
155         B       12.250         17.94           78.27      460.3   
502         B       12.540         16.32           81.25      476.3   
494         B       13.160         20.54           84.06      538.7   
517         M       19.890         20.26          130.50     1214.0   
222         B       10.180         17.53           65.12      313.1   
199         M       14.450         20.22           94.49      642.7   
358         B        8.878         15.49           56.74      241.0   
405         B       10.940         18.59           70.39      370.0   
195         B       12.910         16.33           82.53      516.4   
350         B       11.660         17.07           73.70      421.0   
23          M       21.160         23.04          137.20     1404.0   
304         B       11.460         18.16           73.59      403.1   
446         M       17.750         28.03          117.30      981.6   
535         M       20.550         20.86          137.80     1308.0   
139         B       11.280         13.39           73.00      384.8   
119         M       17.950         20.01          114.20      982.0   
238         B       14.220         27.85           92.55      623.9   
120         B       11.410         10.82           73.34      403.3   
247         B       12.890         14.11           84.95      512.2   
378         B       13.660         15.15           88.27      580.6   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
155          0.08654           0.06679        0.038850              0.02331   
502          0.11580           0.10850        0.059280              0.03279   
494          0.07335           0.05275        0.018000              0.01256   
517          0.10370           0.13100        0.141100              0.09431   
222          0.10610           0.08502        0.017680              0.01915   
199          0.09872           0.12060        0.118000              0.05980   
358          0.08293           0.07698        0.047210              0.02381   
405          0.10040           0.07460        0.049440              0.02932   
195          0.07941           0.05366        0.038730              0.02377   
350          0.07561           0.03630        0.008306              0.01162   
23           0.09428           0.10220        0.109700              0.08632   
304          0.08853           0.07694        0.033440              0.01502   
446          0.09997           0.13140        0.169800              0.08293   
535          0.10460           0.17390        0.208500              0.13220   
139          0.11640           0.11360        0.046350              0.04796   
119          0.08402           0.06722        0.072930              0.05596   
238          0.08223           0.10390        0.110300              0.04408   
120          0.09373           0.06685        0.035120              0.02623   
247          0.08760           0.13460        0.137400              0.03980   
378          0.08268           0.07548        0.042490              0.02471   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
155         0.1970  ...        13.590          25.22            86.60   
502         0.1943  ...        13.570          21.40            86.67   
494         0.1713  ...        14.500          28.46            95.29   
517         0.1802  ...        23.730          25.23           160.50   
222         0.1910  ...        11.170          22.84            71.94   
199         0.1950  ...        18.330          30.12           117.90   
358         0.1930  ...         9.981          17.70            65.27   
405         0.1486  ...        12.400          25.58            82.76   
195         0.1829  ...        13.880          22.00            90.81   
350         0.1671  ...        13.280          19.74            83.61   
23          0.1769  ...        29.170          35

In [73]:
X_train , X_test , y_train , y_test = train_test_split(df.iloc[: , 1:] , df.iloc[: , 0] , test_size = 0.2)

In [74]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [75]:
print(X_test)

[[-0.88277516 -0.32229485 -0.86258697 ... -0.52327113 -1.06275017
  -0.45302658]
 [ 0.59598153 -0.28433646  0.66635163 ...  0.79360032 -0.24323844
   0.9563629 ]
 [-0.96368826  1.07583917 -0.95732464 ... -0.7677153   0.76575577
  -0.25119889]
 ...
 [-0.41403719  0.81223925 -0.42631602 ...  0.0229939  -0.15481328
   0.4481462 ]
 [ 0.24163795 -0.66813795  0.16559538 ... -0.43978876 -0.82116001
  -1.08720322]
 [ 0.97543608  0.67727608  1.07237022 ...  1.16215122 -0.98379914
   1.73935706]]


In [76]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [77]:
y_train

array([0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,

In [78]:
import torch

In [87]:
X_train_torch = torch.from_numpy(X_train)
X_test_torch = torch.from_numpy(X_test)
y_train_torch = torch.from_numpy(y_train)
y_test_torch = torch.from_numpy(y_test)

y_train_torch = y_train_torch.type(torch.float64)
y_test_torch = y_test_torch.type(torch.float64)

In [80]:
y_train_torch.shape

torch.Size([455])

In [81]:
X_train_torch.shape

torch.Size([455, 30])

#DEFINING THE MODEL

In [96]:
class MySimpleNN():
  def __init__(self , X):

    #setting number of weights = no of features + a constant
    self.weights = torch.rand(X.shape[1] , 1 , dtype = torch.float64 , requires_grad = True)
    self.bias = torch.zeros(1 , dtype = torch.float64 , requires_grad = True)

  def forward(self , X):
    z = torch.matmul(X , self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss


In [97]:
#Hyperpara
learning_rate = 0.1
epochs = 25

Training pipeline

In [98]:
model = MySimpleNN(X_train_torch)
model.weights

for e in range(epochs):

  #forward pass
  y_pred = model.forward(X_train_torch)

  ##loss
  loss = model.loss_function(y_pred , y_train_torch)
  print(f'FOR EPOCH {e} , LOSS : {loss.item()}')

  ###backwward pass
  loss.backward()

  ####para updates
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad


#zero gradienr
model.weights.grad.zero_()
model.bias.grad.zero_()




FOR EPOCH 0 , LOSS : 3.7460011026718636
FOR EPOCH 1 , LOSS : 3.637066051666562
FOR EPOCH 2 , LOSS : 3.403644088962664
FOR EPOCH 3 , LOSS : 3.027402356267012
FOR EPOCH 4 , LOSS : 2.5013735009067313
FOR EPOCH 5 , LOSS : 1.8390239319399584
FOR EPOCH 6 , LOSS : 1.1992213121740778
FOR EPOCH 7 , LOSS : 1.1302239055516035
FOR EPOCH 8 , LOSS : 1.700753781123105
FOR EPOCH 9 , LOSS : 2.3467839230788186
FOR EPOCH 10 , LOSS : 2.8497523020253857
FOR EPOCH 11 , LOSS : 3.1764866758936066
FOR EPOCH 12 , LOSS : 3.328795748755684
FOR EPOCH 13 , LOSS : 3.3231328040386523
FOR EPOCH 14 , LOSS : 3.167380792250657
FOR EPOCH 15 , LOSS : 2.8747507152362535
FOR EPOCH 16 , LOSS : 2.461749587317517
FOR EPOCH 17 , LOSS : 1.9770095672560362
FOR EPOCH 18 , LOSS : 1.5619926938714568
FOR EPOCH 19 , LOSS : 1.4907612091517415
FOR EPOCH 20 , LOSS : 1.796734879439297
FOR EPOCH 21 , LOSS : 2.2599551566566096
FOR EPOCH 22 , LOSS : 2.703600214933737
FOR EPOCH 23 , LOSS : 3.0569874601305282
FOR EPOCH 24 , LOSS : 3.27889219064

tensor([0.], dtype=torch.float64)

EVALUATION

In [101]:
with torch.no_grad():
  y_pred = model.forward(X_test_torch)
  y_pred = (y_pred > 0.5).float()

  acc =  (y_pred == y_test_torch).float().mean()
  print(f'ACC : {acc.item()}')
  print(y_pred)

ACC : 0.5355494022369385
tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [