<a href="https://colab.research.google.com/github/SRMannan/Pytorch_L1/blob/main/5_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **torch.nn Module in PyTorch**

The `torch.nn` module in PyTorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively. It abstracts the complexity of creating and training neural networks by offering pre-built layers, loss functions, activation functions, and other utilities, enabling you to focus on designing and experimenting with model architectures.

---

## **Key Components of `torch.nn`:**

### **1. Modules (Layers):**
- **`nn.Module`**: The base class for all neural network modules. Your custom models and layers should subclass this class.
- **Common Layers**:
  - `nn.Linear`: Fully connected layer.
  - `nn.Conv2d`: Convolutional layer.
  - `nn.LSTM`: Recurrent layer.
  - Many more layers are available for different use cases.

---

### **2. Activation Functions:**
- Introduce non-linearities to the model, allowing it to learn complex patterns.
- Examples:
  - `nn.ReLU`: Rectified Linear Unit.
  - `nn.Sigmoid`: Sigmoid activation function.
  - `nn.Tanh`: Hyperbolic tangent function.

---

### **3. Loss Functions:**
- Quantify the difference between the model's predictions and the actual targets.
- Examples:
  - `nn.CrossEntropyLoss`: For classification tasks.
  - `nn.MSELoss`: Mean Squared Error Loss.
  - `nn.NLLLoss`: Negative Log Likelihood Loss.

---

### **4. Container Modules:**
- **`nn.Sequential`**:
  - A sequential container to stack layers in order.
  - Example:
    ```python
    model = nn.Sequential(
        nn.Linear(10, 50),
        nn.ReLU(),
        nn.Linear(50, 1)
    )
    ```

---

### **5. Regularization and Dropout:**
- Helps prevent overfitting and improves the model's ability to generalize to new data.
- Examples:
  - `nn.Dropout`: Randomly zeroes some of the elements of the input tensor during training.
  - `nn.BatchNorm2d`: Batch normalization for 2D input, normalizing layer activations.

---

**Note**: PyTorch's `torch.nn` module, when combined with `torch.optim` and `torch.autograd`, provides a powerful toolkit for creating, training, and fine-tuning neural networks.



In [2]:
 import torch
 import torch.nn as nn

In [3]:
#create model class
class Model(nn.Module):
  def __init__(self , num_features):

    #invocking const of parent class
    super().__init__()
    self.linear = nn.Linear(num_features , 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self , features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [16]:
##for simplicity we are making our own dataset
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.7108],
        [0.6083],
        [0.6163],
        [0.7298],
        [0.6235],
        [0.6416],
        [0.7315],
        [0.6912],
        [0.6893],
        [0.6772]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear.weight

Parameter containing:
tensor([[ 0.1528,  0.2312, -0.3200,  0.0050,  0.1196]], requires_grad=True)

In [7]:
model.linear.bias

Parameter containing:
tensor([0.0899], requires_grad=True)

In [8]:
!pip install torchinfo

In [9]:
from torchinfo import summary

summary(model , input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Neural Network Architecture

1. **Input Layer**:
   - Contains **5 features** as input.

2. **Hidden Layer**:
   - **3 neurons** in the hidden layer.
   - Activation function: **ReLU**.

3. **Output Layer**:
   - **1 neuron** for binary classification.
   - Activation function: **Sigmoid**.

**Summary:**
- Input → Hidden Layer (3 neurons, ReLU) → Output Layer (1 neuron, Sigmoid)


In [28]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, no_of_features):
        super().__init__()
        self.Linear1 = nn.Linear(no_of_features, 3)  # Adjusted input size to be dynamic
        self.relu = nn.ReLU()
        self.Linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, no_of_features):
        out = self.Linear1(no_of_features)
        out = self.relu(out)
        out = self.Linear2(out)
        out = self.sigmoid(out)
        return out

In [29]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.3665],
        [0.3459],
        [0.3723],
        [0.3477],
        [0.3764],
        [0.3681],
        [0.3571],
        [0.3658],
        [0.3510],
        [0.3485]], grad_fn=<SigmoidBackward0>)

# Sequential Containers in PyTorch

## Overview
In PyTorch, **Sequential** is a container module used to define a neural network layer by layer in a linear manner. It allows the user to stack layers and operations without explicitly defining a `forward()` method. It is particularly useful when creating simple models where layers are applied in sequence, and there are no complex branchings.

## Key Points
- **Definition**: `nn.Sequential` is a container that allows the layers or operations to be added sequentially.
- **Layer Stack**: Layers are stacked in the order they are defined and are executed in the same order during the forward pass.
- **Simplification**: It simplifies model construction by eliminating the need to manually define the forward pass for models with a simple structure.

## Syntax
```python
import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(in_features, out_features),
    nn.ReLU(),
    nn.Linear(out_features, 1),
    nn.Sigmoid()
)


In [33]:
class Model(nn.Module):
  def __init__(self , no_of_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(no_of_features , 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self , no_of_features):
    out = self.network(no_of_features)
    return out

In [34]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.5186],
        [0.5307],
        [0.5323],
        [0.5253],
        [0.5341],
        [0.5317],
        [0.5241],
        [0.5439],
        [0.5263],
        [0.5260]], grad_fn=<SigmoidBackward0>)