<a href="https://colab.research.google.com/github/SRMannan/Pytorch_L1/blob/main/2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
print(torch.cuda.is_available())

True


**CREATING TENSOR**

In [3]:
#using empty
a = torch.empty(2,3)
print(type(a))

<class 'torch.Tensor'>


In [4]:
#using zeros
torch.zeros(5,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [5]:
#using ones
torch.ones(5,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [6]:
#using rand
torch.rand(4,5)

## downside is that for every new runtime , new value , for this we use seed

tensor([[0.1167, 0.0653, 0.1163, 0.2481, 0.1579],
        [0.1927, 0.4531, 0.4645, 0.8126, 0.5238],
        [0.9956, 0.9836, 0.6922, 0.9144, 0.4530],
        [0.3094, 0.3342, 0.0327, 0.1164, 0.4638]])

In [7]:
#manual seed
torch.manual_seed(100)
torch.rand(6,7)

tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765, 0.7539, 0.2627],
        [0.0428, 0.2080, 0.1180, 0.1217, 0.7356, 0.7118, 0.7876],
        [0.4183, 0.9014, 0.9969, 0.7565, 0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770, 0.4440, 0.9478, 0.7445, 0.4892],
        [0.2426, 0.7003, 0.5277, 0.2472, 0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064, 0.1629, 0.8902, 0.5163, 0.0359]])

In [8]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
#torch arange
torch.arange(0,19,3)

tensor([ 0,  3,  6,  9, 12, 15, 18])

In [10]:
#using eye
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

**TENSOR SHAPE**

In [11]:
x = torch.tensor([[1,2,3] , [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
#copy a given tensor shape and empty
torch.empty_like(x)

tensor([[      127510864, 136359423185008,               0],
        [              0,               0,               0]])

In [14]:
#copy a given tensor shape and zeros
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
#copy a given tensor shape and ones
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
#copy a given tensor shape and rand
torch.rand_like(x)

##the above like wont work , since entries of x are int , not float
## so specify longs

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [17]:
#find tensor datatype
x.dtype

torch.int64

In [18]:
#assign dtype to tensor
y = torch.tensor([1,2,3] , dtype = torch.float32)

In [19]:
torch.rand_like(y)

tensor([0.6476, 0.3430, 0.3182])

**MATHEMATICAL OPS ON TENSORS**

In [20]:
x = torch.rand(2,2)
x

tensor([[0.5261, 0.0447],
        [0.5123, 0.9051]])

In [21]:
#addition operation
print(f'x+2 : {x+2}')

#subtraction
print(f'x-2 : {x-2}')

#multi
print(f'x*2 : {x*2}')

#div
print(f'x/2 : {x/2}')

#int div
print(f'(x*100)//2 : {(x*100) // 2}')

##pow
print(f'x^2 : {x**2}')

x+2 : tensor([[2.5261, 2.0447],
        [2.5123, 2.9051]])
x-2 : tensor([[-1.4739, -1.9553],
        [-1.4877, -1.0949]])
x*2 : tensor([[1.0522, 0.0893],
        [1.0247, 1.8102]])
x/2 : tensor([[0.2630, 0.0223],
        [0.2562, 0.4525]])
(x*100)//2 : tensor([[26.,  2.],
        [25., 45.]])
x^2 : tensor([[0.2768, 0.0020],
        [0.2625, 0.8192]])


*2 TENSOR OPS*

In [22]:
y = torch.rand(2,2)
y

print(f'x+y : {x+y}')
print(f'x-y : {x-y}')
print(f'x*y : {x*y}')
print(f'x/y : {x/y}')
print(f'x//y : {x//y}')
print(f'x^y : {x**y}')



x+y : tensor([[1.1249, 0.4897],
        [1.2402, 1.3613]])
x-y : tensor([[-0.0728, -0.4003],
        [-0.2155,  0.4488]])
x*y : tensor([[0.3151, 0.0199],
        [0.3729, 0.4129]])
x/y : tensor([[0.8785, 0.1004],
        [0.7039, 1.9837]])
x//y : tensor([[0., 0.],
        [0., 1.]])
x^y : tensor([[0.6807, 0.2507],
        [0.6146, 0.9555]])


In [23]:
z = torch.tensor([1.0 , 2.1 , -3.5 , -4.73 , 5.76 , 8.9])
z

tensor([ 1.0000,  2.1000, -3.5000, -4.7300,  5.7600,  8.9000])

In [24]:
#abs
torch.abs(z)

tensor([1.0000, 2.1000, 3.5000, 4.7300, 5.7600, 8.9000])

In [25]:
#neg
torch.neg(z)

#||y we have ceil , floor , round etc

tensor([-1.0000, -2.1000,  3.5000,  4.7300, -5.7600, -8.9000])

In [26]:
#clamp
#useful to keep numbers within a given range only
torch.clamp(z , min = 1 , max = 5)

tensor([1.0000, 2.1000, 1.0000, 1.0000, 5.0000, 5.0000])

**REDUCTION OPS**

In [30]:
q = torch.randint(low = 0 , high = 6 , size = (2,3) , dtype = torch.float32)
q

tensor([[5., 3., 1.],
        [4., 4., 3.]])

In [31]:
#summing the whole tensor
print(f'SUMMING WHOLE TENSOR : {torch.sum(q)}')

#summing along the cols
print(f'SUMMING ALONG COLS : {torch.sum(q , dim = 0)}')

#summing alon the rows
print(f'SUMMING ALONG ROWS : {torch.sum(q , dim = 1)}')

SUMMING WHOLE TENSOR : 20.0
SUMMING ALONG COLS : tensor([9., 7., 4.])
SUMMING ALONG ROWS : tensor([ 9., 11.])


In [32]:
#calc mean
torch.mean(q)

tensor(3.3333)

In [34]:
#along cols
torch.mean(q , dim = 0)
#mean along rows
torch.mean(q , dim = 1)

tensor([3.0000, 3.6667])

In [36]:
print(f'MAXUM : {torch.max(q)}')
print(f'MINIM : {torch.min(q)}')


MAXUM : 5.0
MINIM : 1.0


**INPLACE OPERATION**

In [40]:
m = torch.tensor([1.2 , 3.4 , 5.6 , 7.8 , 9.77])
n = torch.tensor([1.55 , 6.78 , 9.88 , 8.77 , 5.43])

#add of m and n takes place and gets stored in m
#effectively it is m = m+n
m.add_(n)

tensor([ 2.7500, 10.1800, 15.4800, 16.5700, 15.2000])

**COPYING A TENSOR**

In [41]:
a = torch.rand(2,3)

In [46]:
#why a = b works but dont work , reason is pointing to the same memory location
##lets see the issue
b = a
print(f'VAL OF B : {b}')

a[0][0] = 0
print(f'VAL OF A AFTER CHANGES : {a}')
print(f'VAL OF B AFTER CHANGES: {b}')

##mem loc of a and b have become the same
print(f'ID OF A : {id(a)}')
print(f'ID OF B : {id(b)}')


VAL OF B : tensor([[0.0000, 0.7775, 0.6179],
        [0.3379, 0.2170, 0.9454]])
VAL OF A AFTER CHANGES : tensor([[0.0000, 0.7775, 0.6179],
        [0.3379, 0.2170, 0.9454]])
VAL OF B AFTER CHANGES: tensor([[0.0000, 0.7775, 0.6179],
        [0.3379, 0.2170, 0.9454]])
ID OF A : 136359423187600
ID OF B : 136359423187600


In [49]:
#copying the tensor
b = a.clone()
print(f'ID OF A : {id(a)}')
print(f'ID OF B : {id(b)}')

ID OF A : 136359423187600
ID OF B : 136358813278448


#MOVING TO THE GPU

In [50]:
device = torch.device('cuda')

In [51]:
d = torch.rand((2,3) , device = device)

#NUMPY TO TORCH & TORCH TO NUMPY

In [52]:
import numpy as np

In [53]:
b = np.array([1,2,3,4,5])

In [54]:
type(b)

numpy.ndarray

In [55]:
c = torch.from_numpy(b)
type(c)

torch.Tensor

In [56]:
c

tensor([1, 2, 3, 4, 5])

In [57]:
 g = c.numpy()
 type(g)

numpy.ndarray